[tools]
"github:lucasew/workspaced" = "0.1.6"

[tasks]
lint = "workspaced codebase lint"
fmt = "workspaced codebase format"

[tasks.test]
depends = ["test:*"]

[tasks."test:dummy"]
run = "true"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."codegen:dummy"]
run = "true"

[tasks.install]
depends = ["install:*"]

[tasks."install:dummy"]
run = "true"

[tasks.ci]
depends = ["lint", "test"]
